version: '3.9'

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    expose:
      - $DB_PORT
    volumes:
      - kirunalabs-db:/var/lib/mysql
volumes:
  kirunalabs-db:
